function getUrlParameterAdv(jsURL){var jsurls = jsURL.split("?");if (jsurls.length > 1){var tempid = jsurls[1].split("="); if(tempid[0] == 'uid'){ return tempid[1]; }else{ return "";}}return "";} var v = document.getElementById("login_top");
document.writeln("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
document.writeln("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
document.writeln("<link href=\"/skin/pcenter/top.css\" rel=\"stylesheet\" type=\"text/css\" />");
//document.writeln("<script type=\"text/javascript\" src=\"/skin/pcenter/home.js\"></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div id=\"comm_top\">");
document.writeln("  <div id=\"comm_top_box\">");
document.writeln("    <div id=\"comm_top_left\" style=\"width:298px;\">");
document.writeln("      <ul style=\"width:298px;\">");
document.writeln("        <li style=\"width:60px;\">");
document.writeln("          <dt><img src=\"/public/images/pcenter/site_icon_01.gif\" /></dt>");
document.writeln("          <dd><a href=\"/index.html\" target=\"_top\">\u9996&nbsp;\u9875</a></dd>");
document.writeln("        </li>");
//document.writeln("        <li style=\"width:75px;\">");
//document.writeln("			<dt><img src=\"/public/images/pcenter/site_icon_05.gif\" /></dt>");
//document.writeln("			<dd><a href=\"/upload_dir/soft/XYT.zip\" target=\"_top\">\u6559\u80B2\u901A</a></dd>");
//document.writeln("		</li>");
//document.writeln("		<li style=\"width:75px;\">");
//document.writeln("			<dt><img src=\"/public/images/pcenter/site_icon_02.gif\" /></dt>");
//document.writeln("			<dd><a href=\"/index.shtml\" target=\"_top\">\u8D44\u6E90\u4E2D\u5FC3</a></dd>");
//document.writeln("		</li>");
//document.writeln("		<li style=\"width:75px;\">");
//document.writeln("			<dt><img src=\"/public/images/pcenter/site_icon_04.gif\" /></dt>");
//document.writeln("			<dd><a href=\"http://www.shsbnu.net/pubIndexAction.fo?method=index&typeid=30&paperid=22\" target=\"_blank\">\u6570\u5B57\u62A5\u520A</a></dd>");
//document.writeln("		</li>");
//document.writeln("        <li>");
//document.writeln("			<dt><img src=\"/public/images/pcenter/site_icon_02.gif\" /></dt>");
//document.writeln("			<dd><a onclick=\"AddFavorite(window.top.location.href,window.parent.document.title)\" style=\"cursor: pointer;\">\u52A0\u5165\u6536\u85CF</a></dd>");
//document.writeln("		</li>");
//document.writeln("        <li>");
//document.writeln("			<dt><img src=\"/public/images/pcenter/site_icon_03.gif\" /></dt>");
//document.writeln("			<dd><a onclick=\"SetHome(this, window.top.location.href)\" style=\"cursor: pointer;\">\u8BBE\u4E3A\u9996\u9875</a></dd>");
//document.writeln("		</li>");
document.writeln("      </ul>");
document.writeln("    </div>");
//document.writeln("   <a id=\"comm_top_right2\" onmousemove=\"document.getElementById('comm_site').style.display='block'\" onmouseout=\"document.getElementById('comm_site').style.display='none'\">&nbsp;&nbsp;\u5E94\u7528\u7CFB\u7EDF</a>");
//document.writeln("      <div id=\"comm_site\" onmousemove=\"this.style.display='block'\" onmouseout=\"this.style.display='none'\">");
//document.writeln("        <ul>");
//document.writeln("            <li class=\"site1\"><a href=\"/index.html\">\u95E8\u6237\u7F51\u7AD9</a></li>");
////document.writeln("			  <li class=\"site2\"><a href=\"/pcenter.do?method=index&mproduct=zxbk\">\u5728\u7EBF\u5907\u8BFE</a></li>");
//document.writeln("			  <li class=\"site3\"><a href=\"/index.shtml\">\u8D44\u6E90\u4E2D\u5FC3</a></li>");
////document.writeln("			  <li class=\"site10\"><a href=\"/pcenter.do?method=index&mproduct=tar\">\u6559\u7814\u4E2D\u5FC3</a></li>");
////document.writeln("			  <li class=\"site11\"><a href=\"/photo.htm\">\u56FE\u5E93\u4E2D\u5FC3</a></li>");
//document.writeln("			  <li class=\"site4\"><a href=\"/vod.htm\">\u5FAE\u8BFE\u7CFB\u7EDF</a></li>");
//document.writeln("			  <li class=\"site5\"><a href=\"/baoxiu.htm\">\u62A5\u4FEE\u7BA1\u7406</a></li>");
//document.writeln("			  <li class=\"site11\"><a href=\"http://www.shsbnu.net/pubIndexAction.fo?method=index&typeid=30&paperid=22\" target=\"_blank\">\u6570\u5B57\u62A5\u520A</a></li>");
////document.writeln("			  <li class=\"site6\"><a href=\"/pcenter.do?method=index&mproduct=file\">\u7F51\u7EDC\u786C\u76D8</a></li>");
////document.writeln("			  <li class=\"site7\"><a href=\"/pcenter.do?method=index&mproduct=msg\">\u6D88\u606F\u7BA1\u7406</a></li>");
////document.writeln("			  <li class=\"site9\"><a href=\"/jxt.htm\">\u5BB6\u6821\u4E92\u901A</a></li>");
//document.writeln("        </ul>");
//document.writeln("      </div>");
document.writeln("	   <iframe name=\"topFrame\" width=\"530\" height=\"33\" style=\"float:right;\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\" scrolling=no src=\"/plogin.do?method=top&unitid=" + getUrlParameterAdv(v.getAttribute('src')) + "\"></iframe>");
document.writeln("  </div>");
document.writeln("  <div class=\"comm_clear\"></div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");
