package com.github.wp.business.pojo.base;

// Generated 2016-8-2 15:14:10 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Where;

/**
 * TDepartment generated by hbm2java
 */
@Entity
@Table(name = "BASE_DEPARTMENT")
@Where(clause="EFFECTFLAG='E'")
public class Tdepartment implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Integer versons;
	private String discriminator;
	private String code;
	private String name;
	private String leader;
	private String tel;
	private Integer sortIdx;
	private Integer step;
	private Character effectflag='E';
	private Timestamp createdTime;
	private String creator;
	private Timestamp lastModifiedTime;
	private String lastOperator;
	
	private List<Tdepartment> departments = new ArrayList<Tdepartment>();
	private Tdepartment department;

	public Tdepartment() {
	}
	
	public Tdepartment(Long id) {
		this.id = id;
	}

	public Tdepartment(long id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public Tdepartment(long id, Integer versons, String discriminator, String code, String name, String leader,
			String tel, Integer sortIdx, Integer step, Character effectflag,
			Timestamp createdTime, String creator, Timestamp lastModifiedTime, String lastOperator) {
		this.id = id;
		this.versons = versons;
		this.discriminator = discriminator;
		this.code = code;
		this.name = name;
		this.leader = leader;
		this.tel = tel;
		this.sortIdx = sortIdx;
		this.step = step;
		this.effectflag = effectflag;
		this.createdTime = createdTime;
		this.creator = creator;
		this.lastModifiedTime = lastModifiedTime;
		this.lastOperator = lastOperator;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)  
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "VERSONS", precision = 22, scale = 0)
	public Integer getVersons() {
		return this.versons;
	}

	public void setVersons(Integer versons) {
		this.versons = versons;
	}

	@Column(name = "DISCRIMINATOR", length = 250)
	public String getDiscriminator() {
		return this.discriminator;
	}

	public void setDiscriminator(String discriminator) {
		this.discriminator = discriminator;
	}

	@Column(name = "CODE", nullable = false, length = 40)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "NAME", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LEADER", length = 20)
	public String getLeader() {
		return this.leader;
	}

	public void setLeader(String leader) {
		this.leader = leader;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "SORT_IDX", precision = 22, scale = 0)
	public Integer getSortIdx() {
		return this.sortIdx;
	}

	public void setSortIdx(Integer sortIdx) {
		this.sortIdx = sortIdx;
	}

	@Column(name = "STEP", precision = 22, scale = 0)
	public Integer getStep() {
		return this.step;
	}

	public void setStep(Integer step) {
		this.step = step;
	}

	@Column(name = "EFFECTFLAG", length = 1)
	public Character getEffectflag() {
		return this.effectflag;
	}

	public void setEffectflag(Character effectflag) {
		this.effectflag = effectflag;
	}

	@Column(name = "CREATED_TIME")
	public Timestamp getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Timestamp createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "LAST_MODIFIED_TIME")
	public Timestamp getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Timestamp lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	@Column(name = "LAST_OPERATOR", length = 20)
	public String getLastOperator() {
		return this.lastOperator;
	}

	public void setLastOperator(String lastOperator) {
		this.lastOperator = lastOperator;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	@Where(clause="EFFECTFLAG='E'")
	public List<Tdepartment> getDepartments() {
		return departments;
	}

	public void setDepartments(List<Tdepartment> departments) {
		this.departments = departments;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Tdepartment getDepartment() {
		return department;
	}

	public void setDepartment(Tdepartment department) {
		this.department = department;
	}

	
}
